# codegen:start {preset: labeler}
check-clean:
  - packages/check-clean/**/*
eslint-plugin-codegen:
  - packages/eslint-plugin-codegen/**/*
expect-type:
  - packages/expect-type/**/*
fs-syncer:
  - packages/fs-syncer/**/*
io-ts-extra:
  - packages/io-ts-extra/**/*
memorable-moniker:
  - packages/memorable-moniker/**/*
# codegen:end
