on:
  issue_comment:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - run: echo issue comment created
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
