name: publish
on: 
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"

        node common/scripts/install-run-rush.js install
        node common/scripts/install-run-rush.js build
        node common/scripts/install-run-rush.js publish --target-branch main --publish --apply
